DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

USE employees_db;



CREATE TABLE dept_info (
  dept_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);



-- CREATE TABLE ROLE_INFO (
CREATE TABLE role_info (
  dept_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);
-- )
-- CREATE TABLE EMPLOYEE_INFO (
 CREATE TABLE employee_info (
  dept_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);
-- )
-- CREATE TABLE ADD_EMPLOYEE (
  CREATE TABLE add_employee (
  dept_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);
-- )
-- CREATE TABLE EDIT_EMPLOYEE (
 CREATE TABLE update_employee (
  dept_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);
-- )
