--  Employee Database
DROP DATABASE IF EXISTS EMPLOYEE_DB;

CREATE DATABASE EMPLOYEE_DB;

USE EMPLOYEE_DB;

DROP TABLE IF EXISTS, DEPT_INFO, ROLE_INFO, EMPLOYEE_INFO, ADD_EMPLOYEE, EDIT_EMPLOYEE,

-- Table showing department names and department ids
CREATE TABLE DEPT_INFO (
  book_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dep_name VARCHAR(30) NOT NULL,

)
-- CREATE TABLE ROLE_INFO (

-- )
-- CREATE TABLE EMPLOYEE_INFO (
 
-- )
-- CREATE TABLE ADD_EMPLOYEE (
  
-- )
-- CREATE TABLE EDIT_EMPLOYEE (
 
-- )
