DROP DATABASE IF EXISTS EMPLOYEES_DB;

CREATE DATABASE EMPLOYEES_DB;

USE EMPLOYEES_DB;

CREATE TABLE DEPARTMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30),
  PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
  ID INT NOT NULL,
  TITLE VARCHAR(30),
  SALARY DECIMAL,
  DEPARTMENT_ID INT,
  FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE EMPLOYEE (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(30),
  LAST_NAME VARCHAR(30),
  ROLE_ID INT,
  MANAGER_ID INT NULL,
  PRIMARY KEY (ID)
);